version = 0.1
[default.build.parameters]
template_file = "c:\\Users\\adams\\OneDrive2\\OneDrive\\Desktop\\VSCode Workspaces\\AWS Cloud Services\\Rest API\\template.yaml"
cached = true
parallel = true
use_container = true
